version: 0.0.{build}
image: Visual Studio 2017
platform: Any CPU
clone_folder: C:\projects\
build:
  project: Graphics_CastlevaniaLegends_GB.sln
  verbosity: minimal
test_script:
- cmd: >-
    mkdir "tests\result"

    cd "src\bin\Debug"

    CL_graphics.exe -u "..\..\..\tests\01_decompressing\packed_data" "..\..\..\tests\result\unpacked_data" "..\..\..\tests\buffer" 0 2048
    
    fc /B "..\..\..\tests\01_decompressing\unpacked_data" "..\..\..\tests\result\unpacked_data"
    
    CL_graphics.exe -p "..\..\..\tests\02_compressing\unpacked_data" "..\..\..\tests\result\packed_data" "..\..\..\tests\buffer"

    fc /B "..\..\..\tests\02_compressing\packed_data" "..\..\..\tests\result\packed_data"

    rmdir /S /Q "..\..\..\tests\result"
artifacts:
- path: src\bin\Debug\CL_graphics.exe
  name: CL Graphics