version: 0.0.{build}
image: Visual Studio 2017
platform: Any CPU
clone_folder: C:\projects\
build:
  project: Graphics_CastlevaniaLegends_GB.sln
  verbosity: minimal
test_script:
- cmd: >-
    mkdir "tests\results\01\"

    cd "src\bin\Debug"

    CL_graphics.exe -u "..\..\..\tests\01_decompressing\packed_data" "..\..\..\tests\results\01\unpacked_data" "..\..\..\tests\buffer" 0 2048
    
    fc /B "..\..\..\tests\01_decompressing\unpacked_data" "..\..\..\tests\results\01\unpacked_data"

    mkdir "tests\results\02\
    
    CL_graphics.exe -p "..\..\..\tests\02_compressing\unpacked_data" "..\..\..\tests\results\02\packed_data" "..\..\..\tests\buffer"

    CL_graphics.exe -u "..\..\..\tests\results\02\packed_data" "..\..\..\tests\results\02\unpacked_data" "..\..\..\tests\buffer" 0 2048

    fc /B "..\..\..\tests\results\01\unpacked_data" "..\..\..\tests\results\02\unpacked_data"

    rmdir /S /Q "..\..\..\tests\results"
artifacts:
- path: src\bin\Debug\CL_graphics.exe
  name: CL Graphics